## WEEK 3--Wrangling Data: Preprocessing 
#### WEEK 3: FRIDAY LAB_02


In [64]:
import numpy as np
import pandas as pd 


#Reading in the IPL dataframe
Match = pd.read_csv('Indian Premium Leaque\Match.csv')

#Verifying that we can see the data
Match.head()

Match_Id Match_Date  Team_Name_Id  Opponent_Team_Id  Season_Id  \
0    335987  18-Apr-08             2                 1          1   
1    335988  19-Apr-08             4                 3          1   
2    335989  19-Apr-08             6                 5          1   
3    335990  20-Apr-08             7                 2          1   
4    335991  20-Apr-08             1                 8          1   

                                   Venue_Name  Toss_Winner_Id Toss_Decision  \
0                       M Chinnaswamy Stadium               2         field   
1  Punjab Cricket Association Stadium, Mohali               3           bat   
2                            Feroz Shah Kotla               5           bat   
3                            Wankhede Stadium               7           bat   
4                                Eden Gardens               8           bat   

   IS_Superover  IS_Result  Is_DuckWorthLewis    Win_Type  Won_By  \
0             0          1                  0     by runs   140.0   
1             0          1                  0     by runs    33.0   
2             0          1                  0  by wickets     9.0   
3             0          1                  0  by wickets     5.0   
4             0          1                  0  by wickets     5.0   

   Match_Winner_Id  Man_Of_The_Match_Id  First_Umpire_Id  Second_Umpire_Id  \
0              1.0                  2.0              470               477   
1              3.0                 19.0              471               487   
2              6.0                 90.0              472               512   
3              2.0                 11.0              473               476   
4              1.0                  4.0              474               486   

    City_Name Host_Country  
0   Bangalore        India  
1  Chandigarh        India  
2       Delhi        India  
3      Mumbai        India  
4     Kolkata        India

1. Data Transformation: Pick three variables whose data types may be more useful as another data type and u transform them to numeric or character/ categorical format.  Then, insert a text section into your notebook and explain in no less than 3 sentences what this transformation will allow you to accomplish analytically later on. (2 points)

In [65]:
Match.dtypes

Match_Id                 int64
Match_Date              object
Team_Name_Id             int64
Opponent_Team_Id         int64
Season_Id                int64
Venue_Name              object
Toss_Winner_Id           int64
Toss_Decision           object
IS_Superover             int64
IS_Result                int64
Is_DuckWorthLewis        int64
Win_Type                object
Won_By                 float64
Match_Winner_Id        float64
Man_Of_The_Match_Id    float64
First_Umpire_Id          int64
Second_Umpire_Id         int64
City_Name               object
Host_Country            object
dtype: object

In [66]:
Match['Won_By'].unique()

array([140.,  33.,   9.,   5.,   6.,   3.,  66.,   7.,  10.,   4.,  13.,
        45.,   8.,  29.,  18.,  23.,  41.,  12.,  65.,  25.,   1.,  14.,
       105.,  19.,  75.,  92.,  11.,  24.,  nan,  27.,  38.,  78.,  16.,
        53.,   2.,  31.,  55.,  98.,  34.,  36.,  39.,  17.,  40.,  67.,
        63.,  37.,  57.,  35.,  22.,  21.,  48.,  26.,  20.,  85.,  32.,
        76., 111.,  82.,  43.,  58.,  28.,  74.,  42.,  59.,  46.,  47.,
        86.,  44.,  87., 130.,  15.,  60.,  77.,  30.,  50.,  93.,  72.,
        62.,  97., 138.,  71., 144.,  80.])

In [67]:
Match['Won_By'] = Match['Won_By'].fillna(0).astype('int')

Match["Match_Winner_Id"] = Match["Match_Winner_Id"].fillna(0).astype('int')

Match["Man_Of_The_Match_Id"] = Match["Man_Of_The_Match_Id"].fillna(0).astype("int")

Match.dtypes[['Won_By', 'Match_Winner_Id', 'Man_Of_The_Match_Id']]

Won_By                 int32
Match_Winner_Id        int32
Man_Of_The_Match_Id    int32
dtype: object

Float variables including the Won_By, Match_Winer_Id and Man_Of_The_Match_Id are converted into int32 interger variables as shown above. The interger type compared to the float data types makes it easy for data processing load. The transformation make it easy to anylyze beetween match winners and MVP players. 

2. Data Substitution: Substitute values in at least two variables. Insert a text section into your notebook and explain in no less than 3 sentences how you decided what values to use for substitution and, in addition to your explanation, show your code. (3 points)

In [68]:
Match.describe(include = ('O'))

Match_Date             Venue_Name Toss_Decision    Win_Type City_Name  \
count         577                    577           577         577       577   
unique        407                     35             2           4        29   
top      9-Apr-11  M Chinnaswamy Stadium         field  by wickets    Mumbai   
freq            2                     58           315         307        77   

       Host_Country  
count           577  
unique            3  
top           India  
freq            500

In [83]:
Match.describe()

Match_Id  Team_Name_Id  Opponent_Team_Id   Season_Id  \
count     577.000000    577.000000        577.000000  577.000000   
mean   591635.963605      5.102253          5.211438    5.029463   
std    196366.642396      3.062703          3.024841    2.486247   
min    335987.000000      1.000000          1.000000    1.000000   
25%    419140.000000      3.000000          3.000000    3.000000   
50%    548353.000000      5.000000          5.000000    5.000000   
75%    734004.000000      7.000000          7.000000    7.000000   
max    981024.000000     13.000000         13.000000    9.000000   

       Toss_Winner_Id  IS_Superover   IS_Result  Is_DuckWorthLewis  \
count      577.000000    577.000000  577.000000         577.000000   
mean         5.192374      0.010399    0.994801           0.025997   
std          3.024680      0.101530    0.071981           0.159263   
min          1.000000      0.000000    0.000000           0.000000   
25%          3.000000      0.000000    1.000000           0.000000   
50%          5.000000      0.000000    1.000000           0.000000   
75%          7.000000      0.000000    1.000000           0.000000   
max         13.000000      1.000000    1.000000           1.000000   

           Won_By  Man_Of_The_Match_Id  First_Umpire_Id  Second_Umpire_Id  
count  577.000000           577.000000       577.000000        577.000000  
mean    17.079723           139.055459       484.098787        495.155979  
std     21.842648           117.430906        10.709012         12.353865  
min      0.000000             0.000000       470.000000        471.000000  
25%      6.000000            40.000000       475.000000        488.000000  
50%      8.000000           104.000000       482.000000        493.000000  
75%     20.000000           208.000000       493.000000        500.000000  
max    144.000000           460.000000       511.000000        521.000000

In [71]:
Match.Match_Winner_Id.replace(0, '', inplace=True)


Match.Match_Winner_Id.unique()

array([1, 3, 6, 2, 5, 4, 8, 7, 10, 9, '', 11, 12, 13], dtype=object)

In [72]:
Match.Man_Of_The_Match_Id.unique()

array([  2,  19,  90,  11,   4,  32,  41,  18,  31,  26,  22,  53,  28,
        20,  44, 118, 100, 101,  81,  29,  49, 102,  77,  73,   1, 149,
       151, 144, 136,  64,  74,  71, 122, 132, 124,  88, 109,  14, 105,
        21, 133,   6, 175,  61, 121, 162, 110, 161, 131, 135,  97, 223,
       154,  27, 186,   9,  40,  57, 196,  23, 147,  52,  50,  89,  38,
        66, 104,  63,  96, 191,  87,  60,  56, 211, 233,  46, 230, 237,
       183, 187, 194, 185, 158, 208, 241, 224, 178, 188,  67, 256, 221,
       201, 210, 346,  83, 248, 125,  39, 273, 167, 231,  94,  65, 126,
         8,  84, 192, 140, 294, 235, 253, 302, 270,  62,  42,   0, 275,
       304, 306,  85,  35, 307, 190, 303, 137, 276, 157, 315, 293, 324,
        10, 236, 322, 321, 451, 335, 232, 214, 345, 340, 254, 310, 120,
       320, 351, 362, 357, 309,  17, 207, 358, 382, 305, 336, 364, 370,
       367, 299, 372, 339, 374, 383, 394, 197, 334, 260, 393, 378, 296,
       458, 371, 216, 400, 163,  15, 403, 355, 460, 308, 106, 35

In [74]:
Match.Man_Of_The_Match_Id.replace('0', '', inplace=True)


Match.Man_Of_The_Match_Id.unique()

array([  2,  19,  90,  11,   4,  32,  41,  18,  31,  26,  22,  53,  28,
        20,  44, 118, 100, 101,  81,  29,  49, 102,  77,  73,   1, 149,
       151, 144, 136,  64,  74,  71, 122, 132, 124,  88, 109,  14, 105,
        21, 133,   6, 175,  61, 121, 162, 110, 161, 131, 135,  97, 223,
       154,  27, 186,   9,  40,  57, 196,  23, 147,  52,  50,  89,  38,
        66, 104,  63,  96, 191,  87,  60,  56, 211, 233,  46, 230, 237,
       183, 187, 194, 185, 158, 208, 241, 224, 178, 188,  67, 256, 221,
       201, 210, 346,  83, 248, 125,  39, 273, 167, 231,  94,  65, 126,
         8,  84, 192, 140, 294, 235, 253, 302, 270,  62,  42,   0, 275,
       304, 306,  85,  35, 307, 190, 303, 137, 276, 157, 315, 293, 324,
        10, 236, 322, 321, 451, 335, 232, 214, 345, 340, 254, 310, 120,
       320, 351, 362, 357, 309,  17, 207, 358, 382, 305, 336, 364, 370,
       367, 299, 372, 339, 374, 383, 394, 197, 334, 260, 393, 378, 296,
       458, 371, 216, 400, 163,  15, 403, 355, 460, 308, 106, 35

The Man_Of_The_Match_Id and Match_Winner_Id have been chosen as they had 0 and they are primary numbers. The variables are replaced with and empty string in place of Zero where there was no instance of the chosen variable. This Makes the dataset analysis to be done without errors due to data tempering.

3. Data Reduction: Pick two variables that could be simplified by binning or bucketing, or by normalization or standardization. Then perform the operation(s) you have chosen. Insert a text section into your notebook and explain in no less than 3 sentences what benefit this may provide for any later analysis. (3 points)

In [84]:
Match.describe()

Match_Id  Team_Name_Id  Opponent_Team_Id   Season_Id  \
count     577.000000    577.000000        577.000000  577.000000   
mean   591635.963605      5.102253          5.211438    5.029463   
std    196366.642396      3.062703          3.024841    2.486247   
min    335987.000000      1.000000          1.000000    1.000000   
25%    419140.000000      3.000000          3.000000    3.000000   
50%    548353.000000      5.000000          5.000000    5.000000   
75%    734004.000000      7.000000          7.000000    7.000000   
max    981024.000000     13.000000         13.000000    9.000000   

       Toss_Winner_Id  IS_Superover   IS_Result  Is_DuckWorthLewis  \
count      577.000000    577.000000  577.000000         577.000000   
mean         5.192374      0.010399    0.994801           0.025997   
std          3.024680      0.101530    0.071981           0.159263   
min          1.000000      0.000000    0.000000           0.000000   
25%          3.000000      0.000000    1.000000           0.000000   
50%          5.000000      0.000000    1.000000           0.000000   
75%          7.000000      0.000000    1.000000           0.000000   
max         13.000000      1.000000    1.000000           1.000000   

           Won_By  Man_Of_The_Match_Id  First_Umpire_Id  Second_Umpire_Id  
count  577.000000           577.000000       577.000000        577.000000  
mean    17.079723           139.055459       484.098787        495.155979  
std     21.842648           117.430906        10.709012         12.353865  
min      0.000000             0.000000       470.000000        471.000000  
25%      6.000000            40.000000       475.000000        488.000000  
50%      8.000000           104.000000       482.000000        493.000000  
75%     20.000000           208.000000       493.000000        500.000000  
max    144.000000           460.000000       511.000000        521.000000

In [85]:
Match.Team_Name_Id.describe()

count    577.000000
mean       5.102253
std        3.062703
min        1.000000
25%        3.000000
50%        5.000000
75%        7.000000
max       13.000000
Name: Team_Name_Id, dtype: float64

In [79]:
Team_bins = np.linspace(Match.Team_Name_Id.min(),Match.Team_Name_Id.max(),4)
labels = ['low', 'medium', 'high']
Match1 = Match
Match1['Team_bins'] = pd.cut(Match1['Team_Name_Id'], bins=Team_bins, labels=labels, include_lowest=True)
Match1.groupby(['Team_bins']).count()

Match_Id  Match_Date  Team_Name_Id  Opponent_Team_Id  Season_Id  \
Team_bins                                                                    
low             331         331           331               331        331   
medium          177         177           177               177        177   
high             69          69            69                69         69   

           Venue_Name  Toss_Winner_Id  Toss_Decision  IS_Superover  IS_Result  \
Team_bins                                                                       
low               331             331            331           331        331   
medium            177             177            177           177        177   
high               69              69             69            69         69   

           Is_DuckWorthLewis  Win_Type  Won_By  Match_Winner_Id  \
Team_bins                                                         
low                      331       331     331              331   
medium                   177       177     177              177   
high                      69        69      69               69   

           Man_Of_The_Match_Id  First_Umpire_Id  Second_Umpire_Id  City_Name  \
Team_bins                                                                      
low                        331              331               331        331   
medium                     177              177               177        177   
high                        69               69                69         69   

           Host_Country  
Team_bins                
low                 331  
medium              177  
high                 69

In [25]:
Match.Opponent_Team_Id.describe()

count    136590.000000
mean        126.643239
std         111.078188
min           1.000000
25%          35.000000
50%          88.000000
75%         192.000000
max         434.000000
Name: Striker_Id, dtype: float64

In [81]:
Opponent_Team_bins = np.linspace(Match.Opponent_Team_Id.min(),Match.Opponent_Team_Id.max(),4)
labels = ['low', 'medium', 'high']
Leaque2 = Match
Match1['Opponent_Team_bins'] = pd.cut(Match1['Opponent_Team_Id'], bins=Opponent_Team_bins, labels=labels, include_lowest=True)
Match1.groupby(['Opponent_Team_bins']).count()

Match_Id  Match_Date  Team_Name_Id  Opponent_Team_Id  \
Opponent_Team_bins                                                         
low                      323         323           323               323   
medium                   185         185           185               185   
high                      69          69            69                69   

                    Season_Id  Venue_Name  Toss_Winner_Id  Toss_Decision  \
Opponent_Team_bins                                                         
low                       323         323             323            323   
medium                    185         185             185            185   
high                       69          69              69             69   

                    IS_Superover  IS_Result  Is_DuckWorthLewis  Win_Type  \
Opponent_Team_bins                                                         
low                          323        323                323       323   
medium                       185        185                185       185   
high                          69         69                 69        69   

                    Won_By  Match_Winner_Id  Man_Of_The_Match_Id  \
Opponent_Team_bins                                                 
low                    323              323                  323   
medium                 185              185                  185   
high                    69               69                   69   

                    First_Umpire_Id  Second_Umpire_Id  City_Name  \
Opponent_Team_bins                                                 
low                             323               323        323   
medium                          185               185        185   
high                             69                69         69   

                    Host_Country  Team_bins  
Opponent_Team_bins                           
low                          323        323  
medium                       185        185  
high                          69         69

Team_Name_Id and Opponent_Team_Id variables have been chosen for the data reduction. This helps bridge ealier registed Teams and later registed teams in terms of overall perfomance against other variables. The Team_Name_Id bining will also be ideal in understanding the importance of being in a smaller team id.

4. Now that you have a better dataset, list TWO (2) important organizational analytical questions that management could ask about the dataset in order to help them make business or organizational decisions. (2 points)

1. What Team had the Most wins in the IPL on 20-Apr-08?
2. Which Cities within the EPL hosted the Most and the least IPL Matches?